version: '3'

services:
  syscoin-websocket:
    image: blockchainfoundryinc/sysws:latest
    ports:
      - 9999:9999
    environment:
      - ZMQ_ADDRESS=tcp://syscoin:38393
    depends_on:
      - syscoin
    restart: always
    links:
      - syscoin
  syscoin:
    image: blockchainfoundryinc/docker-syscoind:4.1.3.1
    volumes:
      - ./syscoin:/syscoin/.syscoin
    restart: always
  blockbook:
    image: blockchainfoundryinc/blockbook
    volumes:
      - ./certs/bbcert.crt:/go/src/blockbook/server/testcert.crt
      - ./certs/bbcert.key:/go/src/blockbook/server/testcert.key
    ports:
      - 9130:9130
    restart: always
    links:
      - syscoin
    depends_on:
      - syscoin