version: '3'

services:
  syscoin-websocket:
    image: blockchainfoundryinc/sysws:latest
    ports:
      - 9999:9999
    environment:
      - ZMQ_ADDRESS=tcp://syscoin:38393
    depends_on:
      - syscoin
  syscoin:
    image: blockchainfoundryinc/docker-syscoind:4.1.3
    volumes:
      - ./syscoin:/syscoin/.syscoin
     